[package]
name = "binstruct"
version = "0.1.0"
authors = ["Flux Xu <fluxxu@gmail.com>"]
edition = "2018"

[dependencies]
binstruct-codegen = { path = "../binstruct-codegen" }

thiserror = "1"
bytes = "0.5.5"
pretty-hex = "0.1"
enumflags2 = "0.6"
lazy_static = "1"